baseURL = "https://Isocyanide.github.io"
title = "Udit Narayan"
theme = "m10c"
paginate = 8

[params]
  author = "Udit"
  description = "Math learner"
 
  [[params.social]]
    name = "github"
    url = "https://github.com/Isocyanide"
  [[params.social]]
    name = "telegram"
    url = "https://t.me/WeirdIndianBoi"
  [privacy]
     [privacy.disqus]
         disable = true
     [privacy.googleAnalytics]
         disable = true
     [privacy.instagram]
         disable = true
     [privacy.twitter]
         disable = true
     [privacy.vimeo]
         disable = true
     [privacy.youtube]
         disable = true

  primaryColor = "#ffffff"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  [params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
